---

- name: Configure /usr/local/etc/dhcpd.conf
  template: >
    dest="/usr/local/etc/dhcpd.conf"
    src="dhcpd.conf.j2"
    owner="root"
    group="wheel"
    mode="0644"
    backup="yes"
  with_dict: bsd_dhcpd_assigned_ip
  notify: restart dhcpd
  tags: config_dhcpd
  
# EOF
...
