---

- name: Debug
  vars:
    msg: |-
         ansible_architecture: {{ ansible_architecture }}
         ansible_os_family: {{ ansible_os_family }}
         ansible_distribution: {{ ansible_distribution }}
         ansible_distribution_major_version: {{ ansible_distribution_major_version }}
         ansible_distribution_version: {{ ansible_distribution_version }}
         ansible_distribution_release: {{ ansible_distribution_release }}
         ansible_python_version: {{ ansible_python_version }}

         freebsd_install_method: {{ freebsd_install_method }}
         freebsd_use_packages: {{ freebsd_use_packages|default(True) }}
         freebsd_install_retries: {{ freebsd_install_retries }}
         freebsd_install_delay: {{ freebsd_install_delay }}

         bsd_dhcpd_install: {{ bsd_dhcpd_install }}
         bsd_dhcpd_sanity: {{ bsd_dhcpd_sanity }}
         bsd_dhcpd_sanity_fatal: {{ bsd_dhcpd_sanity_fatal }}
         bsd_dhcpd_enable: {{ bsd_dhcpd_enable }}
         bsd_dhcpd_backup_conf: {{ bsd_dhcpd_backup_conf }}
         bsd_dhcpd_service: {{ bsd_dhcpd_service }}

         bsd_dhcpd_template: {{ bsd_dhcpd_template }}
         bsd_dhcpd_domain_name: {{ bsd_dhcpd_domain_name }}
         bsd_dhcpd_domain_name_servers: {{ bsd_dhcpd_domain_name_servers }}
         bsd_dhcpd_netbios_name_servers: {{ bsd_dhcpd_netbios_name_servers }}
         bsd_dhcpd_default_lease_time: {{ bsd_dhcpd_default_lease_time }}
         bsd_dhcpd_max_lease_time: {{ bsd_dhcpd_max_lease_time }}
         bsd_dhcpd_ddns_update_style: {{ bsd_dhcpd_ddns_update_style }}
         bsd_dhcpd_always_broadcast: {{ bsd_dhcpd_always_broadcast }}
         bsd_dhcpd_log_facility: {{ bsd_dhcpd_log_facility }}
         bsd_dhcpd_authoritative: {{ bsd_dhcpd_authoritative }}

         bsd_dhcpd_wired_lan_subnet: {{ bsd_dhcpd_wired_lan_subnet }}
         bsd_dhcpd_wired_lan_netmask: {{ bsd_dhcpd_wired_lan_netmask }}
         bsd_dhcpd_wired_lan_routers: {{ bsd_dhcpd_wired_lan_routers }}
         bsd_dhcpd_wired_lan_subnet_from: {{ bsd_dhcpd_wired_lan_subnet_from }}
         bsd_dhcpd_wired_lan_subnet_to: {{ bsd_dhcpd_wired_lan_subnet_to }}
         bsd_dhcpd_wired_lan_subnet_broadcast: {{ bsd_dhcpd_wired_lan_subnet_broadcast }}

         bsd_dhcpd_wireless_subnet: {{ bsd_dhcpd_wireless_subnet }}
         bsd_dhcpd_wireless_netmask: {{ bsd_dhcpd_wireless_netmask }}
         bsd_dhcpd_wireless_routers: {{ bsd_dhcpd_wireless_routers }}
         bsd_dhcpd_wireless_subnet_from: {{ bsd_dhcpd_wireless_subnet_from }}
         bsd_dhcpd_wireless_subnet_to: {{ bsd_dhcpd_wireless_subnet_to }}
         bsd_dhcpd_wireless_subnet_broadcast: {{ bsd_dhcpd_wireless_subnet_broadcast }}

         bsd_dhcpd_assigned_ip:
           {{ bsd_dhcpd_assigned_ip|to_yaml(indent=2)|indent(2) }}

         bsd_dhcpd_version: {{ bsd_dhcpd_version }}
         bsd_dhcpd_packages:
           {{ bsd_dhcpd_packages|to_nice_yaml(indent=2)|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
...
