---
# tasks freebsd-dhcp

- import_tasks: debug.yml
  when: bsd_dhcpd_debug
  tags: dhcp_debug

- import_tasks: packages.yml
  tags: dhcp_packages

- include: config_rcconf.yml
  tags: dhcp_rcconf

- include: config_dhcpd.yml
  tags: dhcp_conf

# EOF
...
