---
# tasks freebsd_dhcp

- import_tasks: sanity.yml
  tags: [bsd_dhcp_sanity, always]

- import_tasks: debug.yml
  when: bsd_dhcpd_debug|bool
  tags: [bsd_dhcp_debug, always]

- import_tasks: packages.yml
  when: bsd_dhcpd_install|bool
  tags: bsd_dhcp_packages

- import_tasks: rcconf.yml
  tags: bsd_dhcp_rcconf

- import_tasks: conf.yml
  tags: bsd_dhcp_conf

# EOF
...
