---
# tasks freebsd-dhcp

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - bsd_dhcp_all

- include: config_rc_conf.yml
  tags:
    - bsd_rc_conf
    - bsd_dhcp_all

- include: config_dhcpd.yml
  tags:
    - bsd_config_dhcpd
    - bsd_dhcp_all

# EOF
...
