---

- name: "packages: Install dhcp packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_dhcp_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install dhcp ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_dhcp_packages }}"
  when: freebsd_install_method == "ports"


# EOF
...
