---

- name: "packages: Install dhcp packages"
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_dhcp_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install dhcp ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_dhcp_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "ports"

# EOF
...
