---

- name: "packages: Install dhcp packages."
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_dhcpd_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install dhcp ports."
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages|default(true) }}"
  loop: "{{ bsd_dhcpd_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "ports"

# EOF
...
