---
- name: "Rcconf: Enable and start dhcpd"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*dhcpd_enable\s*=(.*)$
    line: dhcpd_enable="YES"
    backup: "{{ bsd_dhcpd_backup_conf }}"
  notify: Enable and start dhcpd
  when: bsd_dhcpd_enable | bool

- name: "Rcconf: Disable and stop dhcpd"
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: ^\s*dhcpd_enable\s*=(.*)$
    line: dhcpd_enable="NO"
    backup: "{{ bsd_dhcpd_backup_conf }}"
  notify: Disable and stop dhcpd
  when: not bsd_dhcpd_enable | bool

# EOF
