---
# handlers freebsd_dhcp

- name: Enable and start dhcpd
  ansible.builtin.service:
    name: "{{ bsd_dhcpd_service }}"
    state: started
    enabled: true

- name: Disable and stop dhcpd
  ansible.builtin.service:
    name: "{{ bsd_dhcpd_service }}"
    state: stopped
    enabled: false

- name: Start dhcpd
  ansible.builtin.service:
    name: "{{ bsd_dhcpd_service }}"
    state: started

- name: Stop dhcpd
  ansible.builtin.service:
    name: "{{ bsd_dhcpd_service }}"
    state: stopped

- name: Restart dhcpd
  ansible.builtin.service:
    name: "{{ bsd_dhcpd_service }}"
    state: restarted
  when: bsd_dhcpd_enable|bool

# EOF
