---
# handlers freebsd-dhcp

- name: enable and start dhcpd
  service:
    name: "{{ bsd_dhcpd_service }}"
    state: started
    enabled: yes

- name: disable and stop dhcpd
  service:
    name: "{{ bsd_dhcpd_service }}"
    state: stopped
    enabled: no

- name: start dhcpd
  service:
    name: "{{ bsd_dhcpd_service }}"
    state: started

- name: stop dhcpd
  service:
    name: "{{ bsd_dhcpd_service }}"
    state: stopped

- name: restart dhcpd
  service:
    name: "{{ bsd_dhcpd_service }}"
    state: restarted
  when: bsd_dhcpd_enable

# EOF
...
